<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Encryptionlib\**" />
    <EmbeddedResource Remove="Encryptionlib\**" />
    <None Remove="Encryptionlib\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Service\StatmentOrchestration\Model\RawBankDetails.cs" />
    <Compile Remove="Service\StatmentOrchestration\OrchestrationContract\CsvExtractor.cs" />
    <Compile Remove="Service\StatmentOrchestration\OrchestrationContract\Interface\ICsvExtractor.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.0.0" />
    <PackageReference Include="EPPlus" Version="7.1.3" />
    <PackageReference Include="Microsoft.AspNetCore.Hosting.Abstractions" Version="2.3.9" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Features" Version="5.0.17" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared.Solution\Core.Ai.Agent\Core.Ai.Agent.csproj" />
    <ProjectReference Include="..\..\Shared.Solution\Core.HttpHandleResults\Core.HttpHandleResults.csproj" />
  </ItemGroup>

</Project>
