<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <!--<ItemGroup>
      <Compile Remove="WeatherForecast.cs" />
   </ItemGroup>-->

	<ItemGroup>
		<PackageReference Include="Microsoft.OpenApi" Version="1.6.14" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
		<PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="6.6.2" />
	</ItemGroup>

	<ItemGroup>
    <ProjectReference Include="..\..\Shared.Solution\Core.AI.Contracts\Core.AI.Contracts.csproj" />
    <ProjectReference Include="..\..\Shared.Solution\Core.AI.Infrastructure\Core.AI.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Shared.Solution\Core.HttpHandleResult\Core.HttpHandleResults.csproj" />
    <ProjectReference Include="..\Server.Domain\Server.Domain.csproj" />
  </ItemGroup>

</Project>
